DROP VIEW luminotes_user_current;
DROP TABLE luminotes_user;
DROP VIEW note_current;
DROP TABLE note;
DROP VIEW notebook_current;
DROP TABLE notebook;
DROP TABLE password_reset;
DROP TABLE user_notebook;
DROP TABLE invite;
DROP TABLE file;
DROP FUNCTION drop_html_tags( text ); 
