DROP VIEW luminotes_user_current;
DROP TABLE luminotes_user;
DROP VIEW luminoes_group_current;
DROP TABLE luminotes_group;
DROP VIEW note_current;
DROP TABLE note;
DROP VIEW notebook_current;
DROP TABLE notebook;
DROP TABLE password_reset;
DROP TABLE download_access;
DROP TABLE user_notebook;
DROP TABLE user_group;
DROP TABLE invite;
DROP TABLE file;
DROP FUNCTION drop_html_tags( text ); 
